# Generated by Django 5.1.4 on 2024-12-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('dance_style', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, default='jocker face.jpg', null=True, upload_to='participants/')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('judges', models.ManyToManyField(related_name='battles', to='base.judge')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='base.participant')),
                ('participant_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='base.participant')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicality', models.PositiveIntegerField(default=0)),
                ('originality', models.PositiveIntegerField(default=0)),
                ('creativity', models.PositiveIntegerField(default=0)),
                ('energy', models.PositiveIntegerField(default=0)),
                ('collision', models.PositiveIntegerField(default=0)),
                ('battle_spirit', models.PositiveIntegerField(default=0)),
                ('move', models.PositiveIntegerField(default=0)),
                ('technique', models.PositiveIntegerField(default=0)),
                ('timing', models.PositiveIntegerField(default=0)),
                ('combo', models.PositiveIntegerField(default=0)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='base.battle')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='base.judge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='base.team')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='team_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_team_one', to='base.team'),
        ),
        migrations.AddField(
            model_name='battle',
            name='team_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_team_two', to='base.team'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to='base.team'),
        ),
    ]
